name: Download BR2

on:
  workflow_call:
    version:
      config-path:
        required: true
        type: string
    

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout buildroot
        uses: actions/checkout@v3
        with:
          repository: buildroot/buildroot
          ref: 2023.02.x
          path: buildroot


  
