# This is a basic workflow to help you get started with Actions

name: ENTRY

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        defconfig: [initrdfs, rootfs]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          path: main

      - name: Checkout buildroot
        uses: actions/checkout@v3
        with:
          repository: buildroot/buildroot
          ref: 2023.02.x
          path: buildroot

      - name: rsync
        run: rsync -amv main/configs/ buildroot/configs/

      # - id: cache
      #   uses: actions/cache@v3
      #   with:
      #     path: |
      #       buildroot/dl
      #     key: ${{ runner.os }}-${{ hashFiles('**/.lock') }}

      # - name: Download Source
      #   if: steps.cache.outputs.cache-hit != 'true'
      #   working-directory: buildroot
      #   run: make source

      - name: run build
        working-directory: buildroot
        run: |
          make ${{ matrix.defconfig }}_defconfig
          make

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.defconfig }}
          path: |
            buildroot/output/images/
