name: trigger

on:
  # push:
  #   branches:
  #     - "main"
  #     - "develop"
  #     - "releases/**"

  schedule:
    # - cron: "0 2 * * 1"
    - cron: "0 2 * * *"

  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  fetch:
    uses: ./.github/workflows/fetch_buildroot_payload.yaml
  main:
    uses: ./.github/workflows/prebuild_buildroot.yaml
    needs: fetch
    with:
      image: ${{ needs.fetch.outputs.image }}
      tag: ${{ needs.fetch.outputs.tag }}
